language: perl
os:
  # - osx
  - linux
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.24"
  - "5.18-shrplib"
  - "5.24-shrplib"
# disable quiet mode for dependency debugging
install: cpanm --installdeps --notest .